spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_ai
    username: postgres
    password: Jesus25@L

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
